name: CustomEnderChest
version: '1.20-1.0.0'
main: com.github.xniter.customenderchest.CustomEnderChest
api-version: '1.20'
author: CraftersLand, X_Niter
website: www.craftersland.net
load: STARTUP
softdepend: [ProtocolLib]
commands:
  bp:
    description: The short command.
  backpack:
    description: The long command.
permissions:
  CustomEnderChest.level.0:
    description: 9 slots enderchest (1 raw).
    default: false
  CustomEnderChest.level.1:
    description: 18 slots enderchest (2 raws).
    default: false
  CustomEnderChest.level.2:
    description: 27 slots enderchest (3 raws).
    default: false
  CustomEnderChest.level.3:
    description: 36 slots enderchest (4 raws).
    default: false
  CustomEnderChest.level.4:
    description: 45 slots enderchest (5 raws).
    default: false
  CustomEnderChest.level.5:
    description: 54 slots enderchest (6 raws).
    default: op
  CustomEnderChest.admin:
    description: Admin command to open others enderchest.
    default: op
  CustomEnderChest.commands:
    description: Open your enderchest via command.
    default: op
